---
functional:
  - Пользователь должен иметь возможность регистрации и авторизации на сайте используя свой e-mail, либо через свой аккаунт в GitHub иил Discord
  - Пользователь должен иметь возможность создавать игры разной тематики, уровня сложности, максимального времени игры и выбора соперника
  - Пользователь должен иметь возможность писать код для решения задачи на любом выбранном им языке и менять его в процессе игры
  - Пользователь должен иметь возможность сыграть тестовую игру без регистрации, при этом игра и соперник выберутся системой
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - Пользователь должен иметь возможность менять язык сайта на стартовой странице или в настройках
  - Пользователю должно быть предложено обучение по пользованию сайта
